export const stories = [
    {
        id: 1,
        profileImg: "https://picsum.photos/seed/behance123/60/60",
        profileName: "Behance",
        title: [
            "Showcasing creative",
            "portfolios and projects",
            "from top designers",
        ],
        linkLabel: "Read More",
        linkSrc: "behance.net",
        storyImg: "https://picsum.photos/seed/behanceStory456/1920/1280",
    },
    {
        id: 2,
        profileImg: "https://picsum.photos/seed/dribbble789/60/60",
        profileName: "Dribbble",
        title: [
            "Design inspiration",
            "and creative work",
            "from around the world",
        ],
        linkLabel: "Explore",
        linkSrc: "dribbble.com",
        storyImg: "https://picsum.photos/seed/dribbbleStory012/1920/1280",
    },
    {
        id: 3,
        profileImg: "https://picsum.photos/seed/awwwards345/60/60",
        profileName: "Awwwards",
        title: [
            "Recognizing the best",
            "web design and development",
            "with prestigious awards",
        ],
        linkLabel: "Visit Site",
        linkSrc: "awwwards.com",
        storyImg: "https://picsum.photos/seed/awwwardsStory678/1920/1280",
    },
    {
        id: 4,
        profileImg: "https://picsum.photos/seed/artstation901/60/60",
        profileName: "ArtStation",
        title: [
            "Discover artwork",
            "from professional artists",
            "in entertainment industry",
        ],
        linkLabel: "View Gallery",
        linkSrc: "artstation.com",
        storyImg: "https://picsum.photos/seed/artstationStory234/1920/1280",
    },
    {
        id: 5,
        profileImg: "https://picsum.photos/seed/pinterest567/60/60",
        profileName: "Pinterest",
        title: [
            "Find ideas and",
            "inspiration for your",
            "next creative project",
        ],
        linkLabel: "Save Ideas",
        linkSrc: "pinterest.com",
        storyImg: "https://picsum.photos/seed/pinterestStory890/1920/1280",
    },
    {
        id: 6,
        profileImg: "https://picsum.photos/seed/adobe123/60/60",
        profileName: "Adobe Create",
        title: [
            "Creative resources",
            "tutorials and insights",
            "for design professionals",
        ],
        linkLabel: "Learn More",
        linkSrc: "create.adobe.com",
        storyImg: "https://picsum.photos/seed/adobeStory456/1920/1280",
    },
];
